authors:
  chris:
    name: Dr Christopher Burr
    description: Senior Researcher in Trustworthy Systems
    avatar: https://github.com/chrisdburr.png
  clau:
    name: Claudia Fischer
    description: Research Assistant
    avatar: https://github.com/claufischer.png
  david:
    name: Professor David Leslie
    description: Director of Ethics and Responsible Innovation Research
    avatar: https://www.turing.ac.uk/sites/default/files/styles/people/public/2018-11/bio_pic_0.jpg?itok=0Ey8l0kg
  sam: 
    name: Sam Nutt
    description: Researcher and Data Ethicist at LOTI (The London Office of Technology and Innovation)
    avatar: https://github.com/SamANutt.png
  orlando:
    name: Orlando Timmerman
    description: MRes student at Artificial Intelligence for Environmental Risk (AI4ER) CDT at the University of Cambridge
    avatar: https://github.com/orlando-code.png
  youmna:
    name: Youmna Hashem
    description: RA in Ethics and Responsible Innovation, AI for Public Services
    avatar: https://github.com/hashem-y.png
